application: nextclimate
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /delete
  script: delete_zip.py
  login: admin

- url: /write_zip
  script: write_zip.py
  login: admin

- url: /addEntry
  script: write_zip.py
  login: admin

- url: /actnow
  script: actnow.py

- url: /stylesheets
  static_dir: skeleton/stylesheets

- url: /javascripts
  static_dir: skeleton/javascripts

- url: /images
  static_dir: skeleton/images

- url: /static
  static_dir: static

- url: /.*
  script: query_zip.py
